AllCops:
  Exclude:
    - '**/*'


Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Layout/LineLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Style/GlobalVars:
  Enable: false
